# permissions for end users to view cvestats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cvestats-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cve-metrics
    app.kubernetes.io/part-of: cve-metrics
    app.kubernetes.io/managed-by: kustomize
  name: cvestats-viewer-role
rules:
  - apiGroups:
      - metrics.scanner.appscode.com
    resources:
      - cvestats
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.scanner.appscode.com
    resources:
      - cvestats/status
    verbs:
      - get
